services:
  - type: web
    name: tri-heal-backend
    runtime: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    plan: free
    healthCheckPath: /health
    envVars:
      - key: FIREBASE_DATABASE_URL
        value: https://tri-heal-dev-d9484-default-rtdb.europe-west1.firebasedatabase.app
      - key: FRONTEND_ORIGIN
        value: https://therapist-dashboard-seven.vercel.app,https://backend-heal.onrender.com
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
